stages:
    - validate
    - plan
    - apply

#image:
 #   name: hashicorp/terraform:light
  #  entrypoint:
   #     - '/usr/bin/env'
    #    - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

before_script:
  - export AWS_ACCESS_KEY=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - rm -rf .terraform
  - terraform init


terraform_validate:
    stage: validate
    script:
        - echo "Kindly perform terraform Validate"
        - terraform validate
    tags:
        - dev

terraform_plan:
    stage: plan
    script:
        - echo "Kindly perform terraform Plan"
        - terraform plan -out "planfile"
    artifacts:
      untracked: false
      when: on_success
      access: all
      expire_in: "1 days"
      paths:
        - "planfile"
    dependencies:
      - terraform_validate
    tags:
        - dev

terraform_apply:
    stage: apply
    script:
        - echo "Kindly perform terraform apply with planfile"
   #     - terraform apply -input=false "planfile" ||  terraform destroy -auto-approve
    dependencies:
      - terraform_plan
    tags:
        - dev