stages:
  - tag

variables:
  GIT_STRATEGY: fetch
  GIT_DEPTH: 0

auto_generate_date_tag:
  stage: tag
  image: alpine/git
  only:
    refs:
      - main
  script:
    - git config user.name "gitlab-ci[bot]"
    - git config user.email "gitlab-ci@example.com"
    - git fetch --tags
    - TODAY=$(date +%Y%m%d)
    - echo "Today's date: $TODAY"
    - LAST_TAG=$(git tag --list "v$TODAY.*" | sort -V | tail -n1)
    - echo "Last tag: $LAST_TAG"
    - if [ -z "$LAST_TAG" ]; then
        NEW_TAG="$TODAY.0";
      else
        LAST_NUMBER=$(echo $LAST_TAG | awk -F. '{print $NF}')
        NEW_NUMBER=$((LAST_NUMBER + 1))
        NEW_TAG="$TODAY.$NEW_NUMBER"
      fi
    - echo "Creating new tag: $NEW_TAG"
    - git tag "$NEW_TAG"
    - git push "https://$GITLAB_USER:$GITLAB_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git" "$NEW_TAG"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: on_success
